
## Pandas-DataFrame And Series

Pandas stands for Python Data Analytics.Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning.\
It provides two primary data structures: Series and DataFrame.\
A Series is a one-dimensional array-like object, while a DataFrame is a _two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes_ (rows and columns).

We can convert 1D numpy array into a Pandas Series
And 2D numpy matrics into a Pandas DataFrame

In [2]:
## Import Pandas libraries
 
import pandas as pd

In [3]:
## Series - A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table. It is labled.

import pandas as pd

data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)
print(type(series))
## The Series is indexed default (0,1,2,3,4)

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
## Create a series from Dict

dic = {
    'a': 1,
    'b': 2,
    'c': 3
}
series_dic = pd.Series(dic)
print(series_dic)
## The keys become index and values become Series values

a    1
b    2
c    3
dtype: int64

In [5]:
data = [12,34,556]
keys = ['a','b','c']
pd.Series(data, index=keys)

a     12
b     34
c    556
dtype: int64

In [6]:
## we can rename the index
dic = {
    'a': 1,
    'b': 2,
    'c': 3
}
pd.Series(data, index=['x','y','z'])

x     12
y     34
z    556
dtype: int64

In [7]:
## DataFrame
## Create DataFrame from dictionaries

data = {
    'Name': ['Mohit', 'Love', 'Surat'],
    'Age': [23,45,24],
    'City': ['Delhi','LA','SF']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age   City
0  Mohit   23  Delhi
1   Love   45     LA
2  Surat   24     SF
<class 'pandas.core.frame.DataFrame'>

In [8]:
## Can convert df to nparray
import numpy as np
np.array(df)

array([['Mohit', 23, 'Delhi'],
       ['Love', 45, 'LA'],
       ['Surat', 24, 'SF']], dtype=object)

In [23]:
## Create df from list of dict

list_data1 = [
    {'Name': ['Mohit', 'Love', 'Surat']},
    {'Age': [23,45,24]},
    {'City': ['Delhi','LA','SF']}
    ]

list_data2 = [
    {'Name':"Mohit",
     "Age":27,
     "City":"BLR"},
     {'Name':"Tenu",
     "Age":26,
     "City":"Mum"},
     {'Name':"Paglu",
     "Age":27,
     "City":"GGN"},
]

print(pd.DataFrame(list_data1), "\nThis is incorrect way of creating df")
pd.DataFrame(list_data1).shape

                   Name           Age             City
0  [Mohit, Love, Surat]           NaN              NaN
1                   NaN  [23, 45, 24]              NaN
2                   NaN           NaN  [Delhi, LA, SF]
This is incorrect way of creating df

(3, 3)

In [10]:
pd.DataFrame(list_data2)

    Name  Age City
0  Mohit   27  BLR
1   Tenu   26  Mum
2  Paglu   27  GGN

In [11]:
## Reading(Loading) a csv file

df = pd.read_csv('sales_data.csv')
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [12]:
## Inspecting Data

df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [13]:
df.tail()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [24]:
df.shape #Gets dimentions (rows, columns)

(3, 3)

In [25]:
## Get a summary of the DataFrame, including data types and non-null values.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [26]:
## Obtain descriptive statistics for numerical columns

df.describe()

             Age
count   3.000000
mean   30.666667
std    12.423097
min    23.000000
25%    23.500000
50%    24.000000
75%    34.500000
max    45.000000

In [14]:
## Accessing the data from df

data = {
    'Name': ['Mohit', 'Love', 'Surat'],
    'Age': [23,45,24],
    'City': ['Delhi','LA','SF']
}

df = pd.DataFrame(data)
df

    Name  Age   City
0  Mohit   23  Delhi
1   Love   45     LA
2  Surat   24     SF

In [15]:
# We can call any column, it actually behaves like a Series
df['Name']

0    Mohit
1     Love
2    Surat
Name: Name, dtype: object

In [16]:
type(df['Name'])

pandas.core.series.Series

In [29]:
## Accessing multiple columns
df[['Name','Age']]

    Name  Age
0  Mohit   23
1   Love   45
2  Surat   24

In [17]:
## Label-based Indexing
## Access row using .loc  when row and column names are known
df.loc[0,'Age']

np.int64(23)

In [18]:
## Another method to access column using iloc (indexloc) opr similar to list opr
print(df.iloc[0])

Name    Mohit
Age        23
City    Delhi
Name: 0, dtype: object

In [19]:
df.iloc[0][0]

C:\Users\mogr1\AppData\Local\Temp\ipykernel_5260\2900375399.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'Mohit'

In [20]:
## Accessing a specified element (name of labels)
df.at[1,'Name'] # pyright: ignore[reportUndefinedVariable]

'Love'

In [21]:
## Accessing a specifoed element using iat (index of element)
df.iat[2,2] # pyright: ignore[reportUndefinedVariable]

'SF'

## Extra Learnings

1

Numpy can have the following datatypes as elements of the array:\
a Numbers (int, float)\
b Strings (fixed-width, variable-width(StringDType))\
c Bool\


* numpy.char module allows vectorized opr on arrays of strings, like splitting, joining, capitalization element-wise