## Data Manipulation using Pandas DataFrame

In [1]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 30, 22, 35],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
})

In [2]:
df

      Name  Age         City
0    Alice   24     New York
1      Bob   30  Los Angeles
2  Charlie   22      Chicago
3    David   35      Houston

In [3]:
## Adding a new column with default values
df['Salary'] = [50000] * len(df)
df

      Name  Age         City  Salary
0    Alice   24     New York   50000
1      Bob   30  Los Angeles   50000
2  Charlie   22      Chicago   50000
3    David   35      Houston   50000

In [4]:
## DEleting a column
df.drop('Salary')
## This gives KeyError: "['Salary'] not found in axis" as Pandas by default searches for 'Salary' in rows (axis=0)

KeyError: "['Salary'] not found in axis"

In [6]:
## To drop a column, we need to specify axis=1
df.drop('Salary', axis=1)

      Name  Age         City
0    Alice   24     New York
1      Bob   30  Los Angeles
2  Charlie   22      Chicago
3    David   35      Houston

In [7]:
df

## But even after dropping the column, we find it still exists in the DataFrame

      Name  Age         City  Salary
0    Alice   24     New York   50000
1      Bob   30  Los Angeles   50000
2  Charlie   22      Chicago   50000
3    David   35      Houston   50000

In [8]:
## To permanently delete the column, we need to pass another argument inplace=True
df.drop('Salary', axis=1, inplace=True)
df

      Name  Age         City
0    Alice   24     New York
1      Bob   30  Los Angeles
2  Charlie   22      Chicago
3    David   35      Houston

In [9]:
df
## Now the 'Salary' column has been permanently removed from the DataFrame
## Or we could have assigned the result back to df like this:
## df = df.drop('Salary', axis=1)

      Name  Age         City
0    Alice   24     New York
1      Bob   30  Los Angeles
2  Charlie   22      Chicago
3    David   35      Houston

In [10]:
## Add age to the column
df['Age'] = df['Age'] + 2
df

      Name  Age         City
0    Alice   26     New York
1      Bob   32  Los Angeles
2  Charlie   24      Chicago
3    David   37      Houston

In [11]:
## Delete any value based on row index
df.drop(0)

      Name  Age         City
1      Bob   32  Los Angeles
2  Charlie   24      Chicago
3    David   37      Houston

In [12]:
## This again does not delete the row permanently. To do that, we can use inplace=True
df

      Name  Age         City
0    Alice   26     New York
1      Bob   32  Los Angeles
2  Charlie   24      Chicago
3    David   37      Houston

In [13]:
## So to permanently delete the row with index 0, we do:
df.drop(0, axis=0, inplace=True)
df

      Name  Age         City
1      Bob   32  Los Angeles
2  Charlie   24      Chicago
3    David   37      Houston

In [14]:
## Some more examples of data manipulation

df = pd.read_csv('data.csv')

In [15]:
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [16]:
## Fetch first 5 rows
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [17]:
## Display last 3 rows
df.tail(3)

          Date Category  Value   Product  Sales Region
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [18]:
# Display the data types of each column
print(f"Data types:\n{df.dtypes}")

Data types:
Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [19]:
# Describe the DataFrame to get statistical summary
print(f"\nStatistical Summary:\n{df.describe()}")
print("Statistical summary is of numeric columns only.")

Statistical Summary:
           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000
Statistical summary is of numeric columns only.

### Handling Missing Values

In [22]:
## Check for null values in the DataFrame
df.isnull()
# Wherever there is a null value, it will show True, else False

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [26]:
## To check if any column has null values
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [27]:
## To check how many null values are there in each column
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [29]:
## To check which rows have null values
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [31]:
## We can create a new DataFrame with only those rows which have null values
df_null = df[df.isnull().any(axis=1)]
df_null

          Date Category  Value   Product  Sales Region
11  2023-01-12        B   60.0  Product2    NaN   West
15  2023-01-16        C    NaN  Product1  895.0  North
17  2023-01-18        C    NaN  Product1  108.0   West
28  2023-01-29        B    NaN  Product3  617.0  North
33  2023-02-03        C   27.0  Product3    NaN   East
35  2023-02-05        B   60.0  Product2    NaN   West
37  2023-02-07        C    2.0  Product1    NaN  North

In [38]:
## To handle null values, we can either drop them or fill them with some value
df_cleaned = df.dropna()  # Drops all rows with any null values
df_cleaned

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
16  2023-01-17        C   93.0  Product2  511.0  South
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
34  2023-02-04        C   70.0  Product3  669.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [35]:
## We can fill null values with a specific value, say 0
df_nulled = df.fillna(0)
df_nulled

## When we replace null values, good practice to create a new DataFrame

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [40]:
## We can also fill null values with the mean of that column by creating a column with filled values
df['Sales_filled_mean'] = df['Sales'].fillna(df['Sales'].mean())
df

          Date Category  Value   Product  Sales Region  Sales_filled_mean
0   2023-01-01        A   28.0  Product1  754.0   East         754.000000
1   2023-01-02        B   39.0  Product3  110.0  North         110.000000
2   2023-01-03        C   32.0  Product2  398.0   East         398.000000
3   2023-01-04        B    8.0  Product1  522.0   East         522.000000
4   2023-01-05        B   26.0  Product3  869.0  North         869.000000
5   2023-01-06        B   54.0  Product3  192.0   West         192.000000
6   2023-01-07        A   16.0  Product1  936.0   East         936.000000
7   2023-01-08        C   89.0  Product1  488.0   West         488.000000
8   2023-01-09        C   37.0  Product3  772.0   West         772.000000
9   2023-01-10        A   22.0  Product2  834.0   West         834.000000
10  2023-01-11        B    7.0  Product1  842.0  North         842.000000
11  2023-01-12        B   60.0  Product2    NaN   West         557.130435
12  2023-01-13        A   70.0  Product3  628.0  South         628.000000
13  2023-01-14        A   69.0  Product1  423.0   East         423.000000
14  2023-01-15        A   47.0  Product2  893.0   West         893.000000
15  2023-01-16        C    NaN  Product1  895.0  North         895.000000
16  2023-01-17        C   93.0  Product2  511.0  South         511.000000
17  2023-01-18        C    NaN  Product1  108.0   West         108.000000
18  2023-01-19        A   31.0  Product2  578.0   West         578.000000
19  2023-01-20        A   59.0  Product1  736.0   East         736.000000
20  2023-01-21        C   82.0  Product3  606.0  South         606.000000
21  2023-01-22        C   37.0  Product2  992.0  South         992.000000
22  2023-01-23        B   62.0  Product3  942.0  North         942.000000
23  2023-01-24        C   92.0  Product2  342.0   West         342.000000
24  2023-01-25        A   24.0  Product2  458.0   East         458.000000
25  2023-01-26        C   95.0  Product1  584.0   West         584.000000
26  2023-01-27        C   71.0  Product2  619.0  North         619.000000
27  2023-01-28        C   56.0  Product2  224.0  North         224.000000
28  2023-01-29        B    NaN  Product3  617.0  North         617.000000
29  2023-01-30        C   51.0  Product2  737.0  South         737.000000
30  2023-01-31        B   50.0  Product3  735.0   West         735.000000
31  2023-02-01        A   17.0  Product2  189.0   West         189.000000
32  2023-02-02        B   63.0  Product3  338.0  South         338.000000
33  2023-02-03        C   27.0  Product3    NaN   East         557.130435
34  2023-02-04        C   70.0  Product3  669.0   West         669.000000
35  2023-02-05        B   60.0  Product2    NaN   West         557.130435
36  2023-02-06        C   36.0  Product3  177.0   East         177.000000
37  2023-02-07        C    2.0  Product1    NaN  North         557.130435
38  2023-02-08        C   94.0  Product1  408.0  South         408.000000
39  2023-02-09        A   62.0  Product1  155.0   West         155.000000
40  2023-02-10        B   15.0  Product1  578.0   East         578.000000
41  2023-02-11        C   97.0  Product1  256.0   East         256.000000
42  2023-02-12        A   93.0  Product3  164.0   West         164.000000
43  2023-02-13        A   43.0  Product3  949.0   East         949.000000
44  2023-02-14        A   96.0  Product3  830.0   East         830.000000
45  2023-02-15        B   99.0  Product2  599.0   West         599.000000
46  2023-02-16        B    6.0  Product1  938.0  South         938.000000
47  2023-02-17        B   69.0  Product3  143.0   West         143.000000
48  2023-02-18        C   65.0  Product3  182.0  North         182.000000
49  2023-02-19        C   11.0  Product3  708.0  North         708.000000

In [47]:
df.dtypes
## To rename a column, we need to give a dictionary with old and new names
df = df.rename(columns={'Date': 'Sale_date'})
df

     Sale_date Category  Value   Product  Sales Region  Sales_filled_mean
0   2023-01-01        A   28.0  Product1  754.0   East         754.000000
1   2023-01-02        B   39.0  Product3  110.0  North         110.000000
2   2023-01-03        C   32.0  Product2  398.0   East         398.000000
3   2023-01-04        B    8.0  Product1  522.0   East         522.000000
4   2023-01-05        B   26.0  Product3  869.0  North         869.000000
5   2023-01-06        B   54.0  Product3  192.0   West         192.000000
6   2023-01-07        A   16.0  Product1  936.0   East         936.000000
7   2023-01-08        C   89.0  Product1  488.0   West         488.000000
8   2023-01-09        C   37.0  Product3  772.0   West         772.000000
9   2023-01-10        A   22.0  Product2  834.0   West         834.000000
10  2023-01-11        B    7.0  Product1  842.0  North         842.000000
11  2023-01-12        B   60.0  Product2    NaN   West         557.130435
12  2023-01-13        A   70.0  Product3  628.0  South         628.000000
13  2023-01-14        A   69.0  Product1  423.0   East         423.000000
14  2023-01-15        A   47.0  Product2  893.0   West         893.000000
15  2023-01-16        C    NaN  Product1  895.0  North         895.000000
16  2023-01-17        C   93.0  Product2  511.0  South         511.000000
17  2023-01-18        C    NaN  Product1  108.0   West         108.000000
18  2023-01-19        A   31.0  Product2  578.0   West         578.000000
19  2023-01-20        A   59.0  Product1  736.0   East         736.000000
20  2023-01-21        C   82.0  Product3  606.0  South         606.000000
21  2023-01-22        C   37.0  Product2  992.0  South         992.000000
22  2023-01-23        B   62.0  Product3  942.0  North         942.000000
23  2023-01-24        C   92.0  Product2  342.0   West         342.000000
24  2023-01-25        A   24.0  Product2  458.0   East         458.000000
25  2023-01-26        C   95.0  Product1  584.0   West         584.000000
26  2023-01-27        C   71.0  Product2  619.0  North         619.000000
27  2023-01-28        C   56.0  Product2  224.0  North         224.000000
28  2023-01-29        B    NaN  Product3  617.0  North         617.000000
29  2023-01-30        C   51.0  Product2  737.0  South         737.000000
30  2023-01-31        B   50.0  Product3  735.0   West         735.000000
31  2023-02-01        A   17.0  Product2  189.0   West         189.000000
32  2023-02-02        B   63.0  Product3  338.0  South         338.000000
33  2023-02-03        C   27.0  Product3    NaN   East         557.130435
34  2023-02-04        C   70.0  Product3  669.0   West         669.000000
35  2023-02-05        B   60.0  Product2    NaN   West         557.130435
36  2023-02-06        C   36.0  Product3  177.0   East         177.000000
37  2023-02-07        C    2.0  Product1    NaN  North         557.130435
38  2023-02-08        C   94.0  Product1  408.0  South         408.000000
39  2023-02-09        A   62.0  Product1  155.0   West         155.000000
40  2023-02-10        B   15.0  Product1  578.0   East         578.000000
41  2023-02-11        C   97.0  Product1  256.0   East         256.000000
42  2023-02-12        A   93.0  Product3  164.0   West         164.000000
43  2023-02-13        A   43.0  Product3  949.0   East         949.000000
44  2023-02-14        A   96.0  Product3  830.0   East         830.000000
45  2023-02-15        B   99.0  Product2  599.0   West         599.000000
46  2023-02-16        B    6.0  Product1  938.0  South         938.000000
47  2023-02-17        B   69.0  Product3  143.0   West         143.000000
48  2023-02-18        C   65.0  Product3  182.0  North         182.000000
49  2023-02-19        C   11.0  Product3  708.0  North         708.000000

In [54]:
## Change data type of a column
df['Value_new'] = df['Value'].astype(int)
df
## NaN values cannot be converted to int, so those will remain NaN (explained at last)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [57]:
## alternatively fill NaN with mean and then do dtype change using astype()
 
df['Value_new'] = df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

,Sale_date,Category,Value,Product,Sales,Region,Sales_filled_mean,Value_new
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26

In [58]:
# Apply a function to a column
df['New_value'] = df['Value'].apply(lambda x: x * 2)
df.head()

,Sale_date,Category,Value,Product,Sales,Region,Sales_filled_mean,Value_new,New_value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0

### Data Aggregating and Grouping

In [59]:
df.head()

,Sale_date,Category,Value,Product,Sales,Region,Sales_filled_mean,Value_new,New_value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0

In [61]:
## On the basis of a column, we can group the data
grouped_mean = df.groupby('Product')['Value'].mean()
grouped_mean

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [89]:
## We can groupby multiple columns
grouped_multi = df.groupby(['Product', 'Region'])['Value'].sum()
grouped_multi

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [64]:
grouped_multi = df.groupby(['Region', 'Product'])['Value'].sum()
grouped_multi

Region  Product
East    Product1    292.0
        Product2     56.0
        Product3    202.0
North   Product1      9.0
        Product2    127.0
        Product3    203.0
South   Product1    100.0
        Product2    181.0
        Product3    215.0
West    Product1    246.0
        Product2    428.0
        Product3    373.0
Name: Value, dtype: float64

In [82]:
## Perform multiple aggregations on grouped data
aggregated = df.groupby('Region')['Value'].agg(['mean', 'sum', 'max', 'count'])
aggregated

             mean     sum   max  count
Region
East    42.307692   550.0  97.0     13
North   37.666667   339.0  71.0      9
South   62.000000   496.0  94.0      8
West    61.588235  1047.0  99.0     17

In [86]:
# Named aggregations

df.groupby('Product').agg(Sales_sum=('Sales','sum'))

          Sales_sum
Product
Product1     8623.0
Product2     7374.0
Product3     9631.0

### MErging and Joining DataFrames

In [75]:
## Creating some DataFrame for practice
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [77]:
## Merge df on Key
merged_df = pd.merge(df1, df2, on='Key', how='inner')
merged_df

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [78]:
pd.merge(df1, df2, on='Key', how='outer')

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [79]:
pd.merge(df1, df2, on='Key', how='left')

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [80]:
pd.merge(df1, df2, on='Key', how='right')

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

### Extra Learnings
1
We can convert Date string into proper datetime in pandas using pd.to_datetime() function.

In [ ]:
## We can convert data types of columns such as Date column to datetime type
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
df['Date'].dtype

dtype('<M8[ns]')

Pandas datetime columns are actually stored using NumPy’s datetime64 type internally.

In [ ]:
type(df['Date'].values)

numpy.ndarray

Because pandas doesn't define its own datetime storage type.
It relies on NumPy’s optimized dtype (datetime64[ns]) for speed.

Pandas does wrap individual timestamps with its own class:

In [ ]:
df['Date'].values.dtype

dtype('<M8[ns]')

In [ ]:
type(df['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

2
Pandas NaN values are inherently float as it internally stores data as Numpy arrays. Thus Pandas by default converts any numerical column with NaN values into float type.
If we try to convert a NaN value to int, it gives an error as Numpy has no way to represent NaN as int.

New Solution:
Pandas has introduced its own data type called nullable integer types like: Int32, Int64 (capital I) - Pandas dtype. So, use these if cleaning data with missing values and need integers.
This is also true for bool (NumPy) and Bool (Pandas)

General Rule to identify if dtype is of Numpy or Pandas is:\

NumPy dtype starts with small letter and cannot have NaN\
Pandas dtype genrally starts with capital letter and can have NaN

3\
groupby normally works with any feature but better with  categorical variables.
Imp --- Only observed values are shown in groupby, if some category has 0 values, it is not shown
To show that, we use 'observed = False' attribute
eg. df.groupby('color', observed=False).size()