## Nominal/ One Hot Encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
## Create a DataFrame
df = pd.DataFrame({
    'color': ['red','green','yellow','black','white','blue']
})

In [4]:
df.head()

    color
0     red
1   green
2  yellow
3   black
4   white

In [5]:
## Create an instance of OneHotEncoder
encoder = OneHotEncoder()

In [7]:
## Perform fit and transform

encoded = encoder.fit_transform(df[['color']]).toarray()
# Creates alphabetically

In [ ]:
encoded_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())  ## use this fn to output feature names

In [9]:
encoded_df

   color_black  color_blue  color_green  color_red  color_white  color_yellow
0          0.0         0.0          0.0        1.0          0.0           0.0
1          0.0         0.0          1.0        0.0          0.0           0.0
2          0.0         0.0          0.0        0.0          0.0           1.0
3          1.0         0.0          0.0        0.0          0.0           0.0
4          0.0         0.0          0.0        0.0          1.0           0.0
5          0.0         1.0          0.0        0.0          0.0           0.0

In [ ]:
## For converting any new values

encoder.transform([['blue']]) ## creates sparse matrix

d:\AI\udemyHandsOn\machineLearning\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1 stored elements and shape (1, 6)>

In [15]:
##Convert to array

encoder.transform([['blue']]).toarray()

d:\AI\udemyHandsOn\machineLearning\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 1., 0., 0., 0., 0.]])

In [16]:
## Concat

df_final = pd.concat([df,encoded_df],axis=1)
df_final

    color  color_black  color_blue  ...  color_red  color_white  color_yellow
0     red          0.0         0.0  ...        1.0          0.0           0.0
1   green          0.0         0.0  ...        0.0          0.0           0.0
2  yellow          0.0         0.0  ...        0.0          0.0           1.0
3   black          1.0         0.0  ...        0.0          0.0           0.0
4   white          0.0         0.0  ...        0.0          1.0           0.0
5    blue          0.0         1.0  ...        0.0          0.0           0.0

[6 rows x 7 columns]