In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_excel('flight_price.xlsx')
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [4]:
df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [ ]:
## Getting basic info about the data

df.info()
## All the features are object type, only Price is int

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [ ]:
df.describe()
## Only deals with numerical type feature

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [ ]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [12]:
## FEATURE JOURNEY
## Handling Data_of_Journey
## Separate Date, Month and Year

df['Date'] = df['Date_of_Journey'].str.split('/').str[0]
df['Month'] = df['Date_of_Journey'].str.split('/').str[1]
df['Year'] = df['Date_of_Journey'].str.split('/').str[2]
for i in  df['Date_of_Journey'].str.split('/'):
    print(i)

['24', '03', '2019']
['1', '05', '2019']
['9', '06', '2019']
['12', '05', '2019']
['01', '03', '2019']
['24', '06', '2019']
['12', '03', '2019']
['01', '03', '2019']
['12', '03', '2019']
['27', '05', '2019']
['1', '06', '2019']
['18', '04', '2019']
['24', '06', '2019']
['9', '05', '2019']
['24', '04', '2019']
['3', '03', '2019']
['15', '04', '2019']
['12', '06', '2019']
['12', '06', '2019']
['27', '05', '2019']
['6', '03', '2019']
['21', '03', '2019']
['3', '04', '2019']
['1', '05', '2019']
['6', '05', '2019']
['9', '06', '2019']
['1', '06', '2019']
['15', '05', '2019']
['18', '06', '2019']
['15', '06', '2019']
['18', '06', '2019']
['1', '05', '2019']
['6', '04', '2019']
['15', '06', '2019']
['18', '05', '2019']
['27', '06', '2019']
['21', '05', '2019']
['18', '05', '2019']
['06', '03', '2019']
['3', '06', '2019']
['21', '05', '2019']
['15', '03', '2019']
['18', '05', '2019']
['6', '05', '2019']
['21', '03', '2019']
['24', '03', '2019']
['27', '05', '2019']
['3', '05', '2019']
['15', '05', '2019']
['27', '06', '2019']
['9', '03', '2019']
['1', '05', '2019']
['24', '03', '2019']
['18', '06', '2019']
['3', '04', '2019']
['24', '03', '2019']
['01', '03', '2019']
['6', '03', '2019']
['6', '05', '2019']
['6', '03', '2019']
['6', '06', '2019']
['3', '04', '2019']
['3', '06', '2019']
['15', '05', '2019']
['24', '05', '2019']
['24', '06', '2019']
['24', '04', '2019']
['6', '05', '2019']
['21', '05', '2019']
['12', '03', '2019']
['1', '06', '2019']
['09', '03', '2019']
['24', '06', '2019']
['24', '06', '2019']
['21', '03', '2019']
['09', '03', '2019']
['3', '04', '2019']
['3', '04', '2019']
['15', '06', '2019']
['21', '03', '2019']
['9', '06', '2019']
['24', '03', '2019']
['6', '05', '2019']
['27', '06', '2019']
['18', '05', '2019']
['06', '03', '2019']
['24', '06', '2019']
['6', '06', '2019']
['1', '04', '2019']
['24', '05', '2019']
['27', '05', '2019']
['6', '03', '2019']
['12', '03', '2019']
['6', '03', '2019']
['21', '04', '2019']
['21', '06', '2019']
['15', '05', '2019']
['3', '06', '2019']
['18', '06', '2019']
['12', '06', '2019']
['15', '05', '2019']
['9', '06', '2019']
['24', '06', '2019']
['12', '05', '2019']
['1', '05', '2019']
['18', '05', '2019']
['27', '03', '2019']
['27', '03', '2019']
['9', '05', '2019']
['24', '05', '2019']
['18', '03', '2019']
['12', '04', '2019']
['12', '05', '2019']
['6', '03', '2019']
['27', '06', '2019']
['18', '05', '2019']
['6', '03', '2019']
['3', '03', '2019']
['12', '06', '2019']
['9', '05', '2019']
['9', '04', '2019']
['3', '05', '2019']
['6', '05', '2019']
['1', '03', '2019']
['12', '05', '2019']
['21', '05', '2019']
['12', '06', '2019']
['6', '05', '2019']
['24', '06', '2019']
['3', '06', '2019']
['21', '03', '2019']
['15', '06', '2019']
['12', '05', '2019']
['15', '06', '2019']
['21', '05', '2019']
['18', '05', '2019']
['6', '06', '2019']
['27', '06', '2019']
['24', '05', '2019']
['3', '03', '2019']
['9', '04', '2019']
['6', '06', '2019']
['15', '06', '2019']
['9', '06', '2019']
['21', '05', '2019']
['21', '05', '2019']
['3', '06', '2019']
['3', '04', '2019']
['24', '06', '2019']
['9', '06', '2019']
['3', '04', '2019']
['21', '03', '2019']
['27', '06', '2019']
['12', '05', '2019']
['24', '05', '2019']
['9', '05', '2019']
['27', '06', '2019']
['03', '03', '2019']
['12', '05', '2019']
['6', '03', '2019']
['1', '05', '2019']
['24', '03', '2019']
['9', '06', '2019']
['9', '05', '2019']
['12', '06', '2019']
['27', '05', '2019']
['3', '03', '2019']
['21', '05', '2019']
['27', '03', '2019']
['27', '05', '2019']
['3', '04', '2019']
['18', '04', '2019']
['9', '06', '2019']
['27', '06', '2019']
['6', '05', '2019']
['12', '06', '2019']
['3', '04', '2019']
['21', '05', '2019']
['6', '05', '2019']
['21', '05', '2019']
['1', '06', '2019']
['27', '03', '2019']
['15', '05', '2019']
['6', '05', '2019']
['12', '05', '2019']
['24', '06', '2019']
['27', '06', '2019']
['6', '06', '2019']
['3', '06', '2019']
['12', '06', '2019']
['03', '03', '2019']
['27', '03', '2019']
['24', '06', '2019']
['27', '06', '2019']
['12', '03', '2019']
['27', '06', '2019']
['12', '06', '2019']
['24', '06', '2019']
['18', '03', '2019']
['27', '03', '2019']
['24', '03', '2019']
['3', '06', '2019']
['24', '04', '2019']
['18', '05', '2019']
['3', '06', '2019']
['18', '04', '2019']
['27', '03', '2019']
['27', '06', '2019']
['21', '05', '2019']
['18', '05', '2019']
['12', '05', '2019']
['6', '06', '2019']
['6', '06', '2019']
['3', '06', '2019']
['1', '06', '2019']
['24', '06', '2019']
['9', '06', '2019']
['1', '06', '2019']
['12', '05', '2019']
['9', '06', '2019']
['12', '04', '2019']
['12', '06', '2019']
['18', '03', '2019']
['9', '05', '2019']
['9', '06', '2019']
['6', '06', '2019']
['3', '03', '2019']
['27', '04', '2019']
['21', '05', '2019']
['27', '05', '2019']
['24', '03', '2019']
['12', '04', '2019']
['18', '05', '2019']
['9', '03', '2019']
['1', '05', '2019']
['1', '05', '2019']
['6', '03', '2019']
['18', '05', '2019']
['15', '03', '2019']
['24', '06', '2019']
['18', '03', '2019']
['6', '06', '2019']
['9', '06', '2019']
['12', '06', '2019']
['18', '03', '2019']
['24', '04', '2019']
['9', '06', '2019']
['15', '05', '2019']
['27', '06', '2019']
['6', '06', '2019']
['3', '03', '2019']
['1', '06', '2019']
['24', '05', '2019']
['27', '03', '2019']
['21', '03', '2019']
['21', '03', '2019']
['9', '05', '2019']
['21', '06', '2019']
['6', '06', '2019']
['3', '06', '2019']
['3', '06', '2019']
['03', '03', '2019']
['18', '03', '2019']
['9', '03', '2019']
['21', '05', '2019']
['21', '03', '2019']
['24', '06', '2019']
['12', '06', '2019']
['1', '03', '2019']
['06', '03', '2019']
['1', '05', '2019']
['12', '06', '2019']
['1', '06', '2019']
['6', '06', '2019']
['9', '04', '2019']
['15', '03', '2019']
['27', '03', '2019']
['12', '06', '2019']
['9', '03', '2019']
['24', '06', '2019']
['12', '06', '2019']
['3', '03', '2019']
['24', '05', '2019']
['6', '06', '2019']
['6', '05', '2019']
['27', '05', '2019']
['12', '05', '2019']
['24', '06', '2019']
['27', '05', '2019']
['12', '03', '2019']
['3', '03', '2019']
['21', '03', '2019']
['6', '06', '2019']
['6', '03', '2019']
['18', '05', '2019']
['6', '05', '2019']
['21', '03', '2019']
['18', '03', '2019']
['6', '06', '2019']
['9', '05', '2019']
['3', '05', '2019']
['27', '06', '2019']
['12', '05', '2019']
['6', '06', '2019']
['9', '03', '2019']
['27', '03', '2019']
['15', '03', '2019']
['6', '06', '2019']
['6', '06', '2019']
['24', '04', '2019']
['21', '05', '2019']
['3', '06', '2019']
['12', '06', '2019']
['3', '03', '2019']
['6', '03', '2019']
['6', '06', '2019']
['21', '05', '2019']
['27', '06', '2019']
['1', '06', '2019']
['15', '03', '2019']
['27', '06', '2019']
['9', '06', '2019']
['15', '06', '2019']
['12', '03', '2019']
['1', '05', '2019']
['27', '05', '2019']
['27', '05', '2019']
['6', '03', '2019']
['24', '03', '2019']
['24', '03', '2019']
['9', '06', '2019']
['21', '03', '2019']
['9', '04', '2019']
['12', '03', '2019']
['24', '05', '2019']
['6', '05', '2019']
['9', '04', '2019']
['3', '06', '2019']
['18', '06', '2019']
['27', '05', '2019']
['15', '06', '2019']
['27', '05', '2019']
['9', '05', '2019']
['24', '06', '2019']
['9', '04', '2019']
['6', '06', '2019']
['27', '05', '2019']
['12', '06', '2019']
['9', '06', '2019']
['24', '04', '2019']
['27', '04', '2019']
['15', '05', '2019']
['15', '06', '2019']
['01', '03', '2019']
['27', '03', '2019']
['1', '06', '2019']
['18', '03', '2019']
['21', '03', '2019']
['21', '06', '2019']
['24', '06', '2019']
['9', '06', '2019']
['24', '03', '2019']
['27', '06', '2019']
['06', '03', '2019']
['24', '03', '2019']
['15', '05', '2019']
['12', '06', '2019']
['3', '03', '2019']
['9', '04', '2019']
['09', '03', '2019']
['15', '04', '2019']
['24', '05', '2019']
['9', '04', '2019']
['3', '04', '2019']
['3', '06', '2019']
['9', '05', '2019']
['27', '03', '2019']
['12', '06', '2019']
['24', '03', '2019']
['18', '03', '2019']
['6', '03', '2019']
['9', '05', '2019']
['9', '04', '2019']
['1', '05', '2019']
['6', '06', '2019']
['27', '03', '2019']
['1', '06', '2019']
['18', '06', '2019']
['18', '05', '2019']
['27', '05', '2019']
['1', '06', '2019']
['9', '05', '2019']
['15', '05', '2019']
['3', '03', '2019']
['21', '05', '2019']
['6', '06', '2019']
['1', '03', '2019']
['3', '06', '2019']
['09', '03', '2019']
['6', '06', '2019']
['12', '03', '2019']
['3', '06', '2019']
['15', '06', '2019']
['09', '03', '2019']
['6', '06', '2019']
['6', '06', '2019']
['21', '05', '2019']
['18', '04', '2019']
['3', '06', '2019']
['12', '06', '2019']
['18', '05', '2019']
['12', '06', '2019']
['21', '05', '2019']
['21', '03', '2019']
['18', '05', '2019']
['24', '03', '2019']
['12', '05', '2019']
['18', '05', '2019']
['6', '03', '2019']
['9', '03', '2019']
['15', '05', '2019']
['18', '05', '2019']
['18', '05', '2019']
['12', '04', '2019']
['21', '05', '2019']
['6', '06', '2019']
['03', '03', '2019']
['15', '05', '2019']
['9', '04', '2019']
['6', '05', '2019']
['12', '04', '2019']
['9', '05', '2019']
['1', '04', '2019']
['18', '04', '2019']
['1', '06', '2019']
['18', '05', '2019']
['3', '03', '2019']
['21', '04', '2019']
['9', '04', '2019']
['6', '06', '2019']
['21', '04', '2019']
['12', '05', '2019']
['18', '05', '2019']
['15', '03', '2019']
['9', '06', '2019']
['6', '04', '2019']
['24', '06', '2019']
['1', '06', '2019']
['15', '05', '2019']
['1', '04', '2019']
['9', '06', '2019']
['1', '06', '2019']
['27', '06', '2019']
['18', '04', '2019']
['6', '06', '2019']
['18', '05', '2019']
['3', '04', '2019']
['27', '06', '2019']
['18', '05', '2019']
['15', '06', '2019']
['3', '06', '2019']
['1', '05', '2019']
['24', '04', '2019']
['09', '03', '2019']
['15', '06', '2019']
['12', '05', '2019']
['6', '03', '2019']
['9', '06', '2019']
['3', '03', '2019']
['3', '05', '2019']
['21', '03', '2019']
['3', '06', '2019']
['24', '06', '2019']
['6', '03', '2019']
['09', '03', '2019']
['3', '03', '2019']
['3', '06', '2019']
['18', '05', '2019']
['3', '04', '2019']
['21', '05', '2019']
['12', '06', '2019']
['18', '05', '2019']
['24', '05', '2019']
['9', '05', '2019']
['21', '04', '2019']
['6', '03', '2019']
['01', '03', '2019']
['18', '05', '2019']
['1', '06', '2019']
['18', '03', '2019']
['01', '03', '2019']
['1', '04', '2019']
['6', '03', '2019']
['6', '06', '2019']
['21', '03', '2019']
['6', '05', '2019']
['6', '06', '2019']
['1', '04', '2019']
['15', '05', '2019']
['12', '06', '2019']
['9', '06', '2019']
['27', '03', '2019']
['18', '05', '2019']
['6', '06', '2019']
['3', '03', '2019']
['27', '05', '2019']
['9', '03', '2019']
['9', '05', '2019']
['21', '05', '2019']
['1', '06', '2019']
['01', '03', '2019']
['9', '03', '2019']
['21', '03', '2019']
['6', '05', '2019']
['27', '06', '2019']
['3', '03', '2019']
['27', '05', '2019']
['15', '05', '2019']
['21', '03', '2019']
['27', '04', '2019']
['3', '03', '2019']
['21', '04', '2019']
['27', '05', '2019']
['21', '05', '2019']
['21', '03', '2019']
['1', '05', '2019']
['27', '05', '2019']
['27', '05', '2019']
['24', '05', '2019']
['24', '04', '2019']
['6', '05', '2019']
['15', '06', '2019']
['6', '06', '2019']
['24', '03', '2019']
['6', '05', '2019']
['9', '05', '2019']
['06', '03', '2019']
['1', '03', '2019']
['6', '04', '2019']
['1', '04', '2019']
['18', '05', '2019']
['24', '04', '2019']
['6', '03', '2019']
['24', '03', '2019']
['24', '03', '2019']
['9', '03', '2019']
['24', '06', '2019']
['12', '06', '2019']
['1', '06', '2019']
['21', '05', '2019']
['24', '04', '2019']
['3', '03', '2019']
['21', '03', '2019']
['9', '03', '2019']
['15', '06', '2019']
['1', '04', '2019']
['9', '05', '2019']
['9', '06', '2019']
['6', '05', '2019']
['15', '05', '2019']
['9', '05', '2019']
['12', '04', '2019']
['15', '06', '2019']
['18', '04', '2019']
['12', '06', '2019']
['1', '06', '2019']
['6', '03', '2019']
['21', '05', '2019']
['21', '06', '2019']
['3', '03', '2019']
['18', '05', '2019']
['6', '04', '2019']
['03', '03', '2019']
['24', '03', '2019']
['27', '05', '2019']
['09', '03', '2019']
['1', '06', '2019']
['1', '03', '2019']
['15', '06', '2019']
['15', '06', '2019']
['21', '04', '2019']
['15', '05', '2019']
['24', '04', '2019']
['18', '05', '2019']
['3', '04', '2019']
['15', '06', '2019']
['18', '05', '2019']
['24', '03', '2019']
['9', '05', '2019']
['15', '03', '2019']
['15', '05', '2019']
['1', '06', '2019']
['21', '04', '2019']
['18', '05', '2019']
['9', '05', '2019']
['21', '05', '2019']
['21', '03', '2019']
['6', '03', '2019']
['1', '06', '2019']
['6', '04', '2019']
['18', '05', '2019']
['15', '04', '2019']
['27', '05', '2019']
['15', '03', '2019']
['1', '06', '2019']
['21', '03', '2019']
['9', '05', '2019']
['1', '04', '2019']
['1', '05', '2019']
['9', '05', '2019']
['1', '05', '2019']
['21', '03', '2019']
['15', '06', '2019']
['27', '03', '2019']
['6', '04', '2019']
['9', '05', '2019']
['27', '05', '2019']
['27', '03', '2019']
['3', '05', '2019']
['1', '05', '2019']
['12', '03', '2019']
['15', '03', '2019']
['15', '06', '2019']
['6', '06', '2019']
['6', '03', '2019']
['12', '03', '2019']
['6', '05', '2019']
['12', '03', '2019']
['15', '03', '2019']
['18', '05', '2019']
['01', '03', '2019']
['6', '05', '2019']
['6', '06', '2019']
['1', '05', '2019']
['3', '05', '2019']
['3', '03', '2019']
['21', '03', '2019']
['27', '04', '2019']
['27', '05', '2019']
['15', '06', '2019']
['21', '05', '2019']
['21', '04', '2019']
['12', '06', '2019']
['21', '05', '2019']
['18', '05', '2019']
['24', '05', '2019']
['27', '03', '2019']
['6', '03', '2019']
['21', '06', '2019']
['12', '06', '2019']
['9', '04', '2019']
['03', '03', '2019']
['06', '03', '2019']
['27', '05', '2019']
['9', '06', '2019']
['3', '05', '2019']
['24', '03', '2019']
['01', '03', '2019']
['15', '05', '2019']
['24', '06', '2019']
['9', '04', '2019']
['27', '03', '2019']
['9', '06', '2019']
['9', '06', '2019']
['24', '04', '2019']
['18', '05', '2019']
['27', '04', '2019']
['3', '03', '2019']
['18', '05', '2019']
['12', '06', '2019']
['3', '06', '2019']
['21', '05', '2019']
['21', '03', '2019']
['6', '06', '2019']
['9', '05', '2019']
['18', '05', '2019']
['18', '06', '2019']
['15', '06', '2019']
['15', '05', '2019']
['3', '05', '2019']
['18', '05', '2019']
['15', '05', '2019']
['9', '05', '2019']
['1', '06', '2019']
['27', '05', '2019']
['12', '06', '2019']
['15', '03', '2019']
['1', '06', '2019']
['21', '03', '2019']
['18', '06', '2019']
['3', '04', '2019']
['27', '06', '2019']
['24', '03', '2019']
['03', '03', '2019']
['12', '05', '2019']
['27', '05', '2019']
['9', '04', '2019']
['18', '03', '2019']
['15', '06', '2019']
['27', '05', '2019']
['9', '05', '2019']
['6', '05', '2019']
['1', '05', '2019']
['24', '03', '2019']
['3', '05', '2019']
['21', '03', '2019']
['21', '05', '2019']
['9', '05', '2019']
['21', '03', '2019']
['15', '06', '2019']
['1', '06', '2019']
['12', '05', '2019']
['27', '03', '2019']
['24', '03', '2019']
['18', '03', '2019']
['1', '04', '2019']
['27', '03', '2019']
['21', '03', '2019']
['12', '06', '2019']
['24', '03', '2019']
['21', '03', '2019']
['15', '06', '2019']
['18', '05', '2019']
['6', '04', '2019']
['15', '05', '2019']
['18', '04', '2019']
['1', '06', '2019']
['21', '03', '2019']
['12', '06', '2019']
['6', '03', '2019']
['21', '05', '2019']
['3', '04', '2019']
['15', '04', '2019']
['12', '05', '2019']
['24', '06', '2019']
['9', '05', '2019']
['1', '06', '2019']
['27', '04', '2019']
['27', '05', '2019']
['9', '06', '2019']
['15', '05', '2019']
['6', '05', '2019']
['1', '06', '2019']
['12', '06', '2019']
['9', '06', '2019']
['09', '03', '2019']
['6', '03', '2019']
['18', '04', '2019']
['15', '05', '2019']
['27', '06', '2019']
['1', '06', '2019']
['27', '06', '2019']
['27', '05', '2019']
['1', '06', '2019']
['9', '06', '2019']
['27', '04', '2019']
['18', '05', '2019']
['24', '03', '2019']
['3', '06', '2019']
['24', '06', '2019']
['3', '03', '2019']
['18', '06', '2019']
['24', '06', '2019']
['3', '06', '2019']
['9', '04', '2019']
['27', '05', '2019']
['9', '05', '2019']
['21', '05', '2019']
['6', '06', '2019']
['9', '05', '2019']
['6', '05', '2019']
['21', '05', '2019']
['3', '03', '2019']
['9', '06', '2019']
['21', '03', '2019']
['15', '05', '2019']
['24', '04', '2019']
['21', '05', '2019']
['24', '05', '2019']
['15', '06', '2019']
['3', '04', '2019']
['21', '03', '2019']
['24', '06', '2019']
['1', '06', '2019']
['27', '06', '2019']
['01', '03', '2019']
['21', '03', '2019']
['6', '03', '2019']
['15', '05', '2019']
['24', '03', '2019']
['9', '05', '2019']
['6', '06', '2019']
['9', '05', '2019']
['09', '03', '2019']
['18', '05', '2019']
['01', '03', '2019']
['9', '04', '2019']
['27', '05', '2019']
['1', '06', '2019']
['3', '03', '2019']
['24', '03', '2019']
['1', '06', '2019']
['12', '06', '2019']
['15', '03', '2019']
['03', '03', '2019']
['6', '03', '2019']
['21', '05', '2019']
['1', '06', '2019']
['18', '05', '2019']
['3', '03', '2019']
['18', '05', '2019']
['15', '05', '2019']
['18', '05', '2019']
['6', '05', '2019']
['18', '06', '2019']
['6', '04', '2019']
['24', '05', '2019']
['21', '05', '2019']
['21', '03', '2019']
['12', '06', '2019']
['21', '06', '2019']
['9', '05', '2019']
['9', '05', '2019']
['9', '06', '2019']
['3', '03', '2019']
['18', '05', '2019']
['01', '03', '2019']
['21', '05', '2019']
['1', '04', '2019']
['21', '05', '2019']
['27', '06', '2019']
['9', '05', '2019']
['9', '05', '2019']
['9', '04', '2019']
['9', '03', '2019']
['18', '05', '2019']
['6', '06', '2019']
['1', '03', '2019']
['18', '05', '2019']
['27', '06', '2019']
['12', '06', '2019']
['15', '06', '2019']
['27', '06', '2019']
['9', '05', '2019']
['24', '05', '2019']
['21', '03', '2019']
['15', '06', '2019']
['18', '06', '2019']
['15', '05', '2019']
['27', '05', '2019']
['9', '06', '2019']
['9', '05', '2019']
['24', '05', '2019']
['6', '06', '2019']
['15', '06', '2019']
['6', '06', '2019']
['24', '05', '2019']
['24', '03', '2019']
['1', '04', '2019']
['1', '05', '2019']
['03', '03', '2019']
['27', '04', '2019']
['27', '06', '2019']
['12', '06', '2019']
['18', '05', '2019']
['9', '05', '2019']
['15', '03', '2019']
['12', '03', '2019']
['6', '06', '2019']
['21', '03', '2019']
['21', '03', '2019']
['6', '03', '2019']
['18', '05', '2019']
['1', '04', '2019']
['27', '06', '2019']
['3', '03', '2019']
['3', '06', '2019']
['27', '06', '2019']
['21', '03', '2019']
['1', '05', '2019']
['6', '06', '2019']
['15', '05', '2019']
['6', '06', '2019']
['27', '05', '2019']
['9', '05', '2019']
['15', '05', '2019']
['27', '06', '2019']
['24', '06', '2019']
['15', '05', '2019']
['9', '06', '2019']
['6', '03', '2019']
['06', '03', '2019']
['9', '03', '2019']
['15', '05', '2019']
['15', '05', '2019']
['3', '03', '2019']
['24', '03', '2019']
['24', '05', '2019']
['24', '03', '2019']
['9', '06', '2019']
['12', '05', '2019']
['9', '05', '2019']
['09', '03', '2019']
['1', '06', '2019']
['27', '05', '2019']
['18', '05', '2019']
['3', '04', '2019']
['21', '04', '2019']
['9', '05', '2019']
['15', '04', '2019']
['21', '05', '2019']
['18', '04', '2019']
['21', '05', '2019']
['1', '04', '2019']
['6', '06', '2019']
['3', '06', '2019']
['3', '03', '2019']
['12', '06', '2019']
['15', '06', '2019']
['12', '05', '2019']
['21', '06', '2019']
['12', '05', '2019']
['27', '03', '2019']
['1', '03', '2019']
['3', '03', '2019']
['6', '03', '2019']
['27', '03', '2019']
['27', '03', '2019']
['21', '03', '2019']
['1', '06', '2019']
['18', '03', '2019']
['24', '03', '2019']
['9', '03', '2019']
['09', '03', '2019']
['21', '03', '2019']
['27', '06', '2019']
['01', '03', '2019']
['9', '05', '2019']
['24', '06', '2019']
['6', '06', '2019']
['9', '06', '2019']
['9', '06', '2019']
['12', '05', '2019']
['21', '05', '2019']
['15', '05', '2019']
['15', '03', '2019']
['01', '03', '2019']
['12', '05', '2019']
['21', '05', '2019']
['12', '05', '2019']
['3', '03', '2019']
['6', '06', '2019']
['3', '06', '2019']
['03', '03', '2019']
['3', '06', '2019']
['12', '05', '2019']
['18', '05', '2019']
['3', '04', '2019']
['18', '05', '2019']
['01', '03', '2019']
['1', '06', '2019']
['27', '05', '2019']
['24', '05', '2019']
['15', '06', '2019']
['18', '05', '2019']
['15', '04', '2019']
['21', '05', '2019']
['09', '03', '2019']
['18', '06', '2019']
['6', '03', '2019']

In [10]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01,03,2019

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  object
 12  Month            10683 non-null  object
 13  Year             10683 non-null  object
dtypes: int64(1), object(13)
memory usage: 1.1+ MB

In [14]:
## Convert the extracted features into int

df['Date'] = df['Date'].astype(int)
df['Month'] = df['Month'].astype(int)
df['Year'] = df['Year'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  int64
 12  Month            10683 non-null  int64
 13  Year             10683 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.1+ MB

In [15]:
## Drop the original date feature (not required)

df.drop('Date_of_Journey', axis=1, inplace=True)

In [ ]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019

In [18]:
## Simplify Arrival time into Hour and minute columns

df['Arrival_Hour'] = df['Arrival_Time'].str.split(':').str[0]
df['Arrival_Min'] = df['Arrival_Time'].str.split(':').str[1]
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,01,10 22 Mar
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019,04,25 10 Jun
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019,21,35

In [19]:
## Still the Arrival_min is not clean

df['Arrival_Min'] = df['Arrival_Min'].apply(lambda x:x.split(' ')[0])

In [20]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019,04,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019,21,35

In [21]:
df['Arrival_Hour'] = df['Arrival_Hour'].astype(int)
df['Arrival_Min'] = df['Arrival_Min'].astype(int)
df.drop('Arrival_Time', axis=1, inplace=True)

In [26]:
## Cleaning Departure Time

df['Departure_Hour'] = df['Dep_Time'].str.split(':').str[0]
df['Departure_Min'] = df['Dep_Time'].str.split(':').str[1]
df.head()

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Departure_Hour,Departure_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15,05,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,6,2019,4,25,09,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218,12,5,2019,23,30,18,05
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302,1,3,2019,21,35,16,50

In [ ]:
df.drop('Dep_Time', axis=1, inplace=True)
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Departure_Hour,Departure_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,13,15,05,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,4,25,09,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,23,30,18,05
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,21,35,16,50

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Duration         10683 non-null  object
 5   Total_Stops      10682 non-null  object
 6   Additional_Info  10683 non-null  object
 7   Price            10683 non-null  int64
 8   Date             10683 non-null  int64
 9   Month            10683 non-null  int64
 10  Year             10683 non-null  int64
 11  Arrival_Hour     10683 non-null  int64
 12  Arrival_Min      10683 non-null  int64
 13  Departure_Hour   10683 non-null  object
 14  Departure_Min    10683 non-null  object
dtypes: int64(6), object(9)
memory usage: 1.2+ MB

In [30]:
df['Departure_Hour'] = df['Departure_Hour'].astype(int)
df['Departure_Min'] = df['Departure_Min'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Duration         10683 non-null  object
 5   Total_Stops      10682 non-null  object
 6   Additional_Info  10683 non-null  object
 7   Price            10683 non-null  int64
 8   Date             10683 non-null  int64
 9   Month            10683 non-null  int64
 10  Year             10683 non-null  int64
 11  Arrival_Hour     10683 non-null  int64
 12  Arrival_Min      10683 non-null  int64
 13  Departure_Hour   10683 non-null  int64
 14  Departure_Min    10683 non-null  int64
dtypes: int64(8), object(7)
memory usage: 1.2+ MB

In [31]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [33]:
df[df['Total_Stops'].isnull()]

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Departure_Hour,Departure_Min
9039,Air India,Delhi,Cochin,NaN,23h 40m,NaN,No info,7480,6,5,2019,9,25,9,45

In [34]:
## Converting Categorical feature into Numerical feature

df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [36]:
df['Total_Stops'] = df['Total_Stops'].map({'non-stop': 0,'2 stops': 2, '1 stop': 1, '3 stops': 3, '4 stops': 4,np.nan: 1})

In [39]:
df[df['Total_Stops'].isnull()]
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Departure_Hour,Departure_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2,No info,7662,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2,No info,13882,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1,No info,6218,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1,No info,13302,1,3,2019,21,35,16,50

In [50]:
## Extracting Duration time

df['Duration_Hour'] = df['Duration'].str.split(' ').str[0].str.split('h').str[0]
df['Duration_Hour']

0         2
1         7
2        19
3         5
4         4
         ..
10678     2
10679     2
10680     3
10681     2
10682     8
Name: Duration_Hour, Length: 10683, dtype: object

In [51]:
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Departure_Hour,Departure_Min,Duration_Hour,Duration_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0,No info,3897,24,3,2019,1,10,22,20,2,2h 50m
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2,No info,7662,1,5,2019,13,15,5,50,7,7h 25m
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2,No info,13882,9,6,2019,4,25,9,25,19,19h
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1,No info,6218,12,5,2019,23,30,18,5,5,5h 25m
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1,No info,13302,1,3,2019,21,35,16,50,4,4h 45m

In [ ]:
## Extracting Duration time
import re

df['Duration_Min'] = df['Duration'].str.split(r'?h ')
df['Duration_Min']

error: nothing to repeat at position 0

### Extra Learnings

str