In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel('my_flight_price.xlsx')
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [6]:
df[df.duplicated(keep=False)]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
33,Jet Airways,15/06/2019,Delhi,Cochin,DEL → NAG → BOM → COK,14:35,12:35 16 Jun,22h,2 stops,In-flight meal not included,10919
49,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,19:00 28 Jun,19h 55m,2 stops,In-flight meal not included,11150
73,Jet Airways,24/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,12:35 25 Jun,13h 30m,2 stops,No info,12819
81,Jet Airways,24/03/2019,Banglore,New Delhi,BLR → DEL,19:55,22:35,2h 40m,non-stop,No info,7229
87,Jet Airways,6/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,09:40,04:25 07 Jun,18h 45m,2 stops,No info,13014
...,...,...,...,...,...,...,...,...,...,...,...
10594,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,12:35 28 Jun,13h 30m,2 stops,No info,12819
10616,Jet Airways,1/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,09:40,12:35 02 Jun,26h 55m,2 stops,No info,13014
10634,Jet Airways,6/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,09:40,12:35 07 Jun,26h 55m,2 stops,In-flight meal not included,11733
10672,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,19:00 28 Jun,19h 55m,2 stops,In-flight meal not included,11150
10673,Jet Airways,27/05/2019,Delhi,Cochin,DEL → AMD → BOM → COK,13:25,04:25 28 May,15h,2 stops,No info,16704

In [7]:
df[df.duplicated(keep=False)].shape[0]

415

In [8]:
key_cols = [
    "Airline",
    "Date_of_Journey",
    "Source",
    "Destination",
    "Dep_Time"
]

df[df.duplicated(subset=key_cols, keep=False)].sort_values(key_cols)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
2266,Air Asia,03/03/2019,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,7074
2773,Air Asia,03/03/2019,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,7652
4851,Air Asia,03/03/2019,Banglore,New Delhi,BLR → DEL,23:25,02:10 04 Mar,2h 45m,non-stop,No info,6135
9107,Air Asia,03/03/2019,Banglore,New Delhi,BLR → DEL,23:25,02:10 07 Mar,2h 45m,non-stop,No info,6477
1459,Air Asia,09/03/2019,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,4284
...,...,...,...,...,...,...,...,...,...,...,...
6586,Vistara,9/06/2019,Kolkata,Banglore,CCU → DEL → BLR,17:00,23:25,6h 25m,1 stop,No info,9870
2873,Vistara,9/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:20,23:25 10 Jun,27h 5m,1 stop,No info,8085
4106,Vistara,9/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:20,18:50 10 Jun,22h 30m,1 stop,No info,8610
7322,Vistara,9/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:20,10:45 10 Jun,14h 25m,1 stop,No info,9397
7625,Vistara,9/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:20,20:20 10 Jun,24h,1 stop,No info,8085

In [9]:
hashes = pd.util.hash_pandas_object(df, index=False)
hashes.duplicated().sum()

np.int64(220)

In [10]:
df.loc[hashes.duplicated(keep=False)]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
33,Jet Airways,15/06/2019,Delhi,Cochin,DEL → NAG → BOM → COK,14:35,12:35 16 Jun,22h,2 stops,In-flight meal not included,10919
49,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,19:00 28 Jun,19h 55m,2 stops,In-flight meal not included,11150
73,Jet Airways,24/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,12:35 25 Jun,13h 30m,2 stops,No info,12819
81,Jet Airways,24/03/2019,Banglore,New Delhi,BLR → DEL,19:55,22:35,2h 40m,non-stop,No info,7229
87,Jet Airways,6/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,09:40,04:25 07 Jun,18h 45m,2 stops,No info,13014
...,...,...,...,...,...,...,...,...,...,...,...
10594,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,12:35 28 Jun,13h 30m,2 stops,No info,12819
10616,Jet Airways,1/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,09:40,12:35 02 Jun,26h 55m,2 stops,No info,13014
10634,Jet Airways,6/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,09:40,12:35 07 Jun,26h 55m,2 stops,In-flight meal not included,11733
10672,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,19:00 28 Jun,19h 55m,2 stops,In-flight meal not included,11150
10673,Jet Airways,27/05/2019,Delhi,Cochin,DEL → AMD → BOM → COK,13:25,04:25 28 May,15h,2 stops,No info,16704

In [11]:
dup_df = df[df.duplicated(keep=False)]

In [12]:
dup_df.shape

(415, 11)

In [13]:
dup_df["_row_hash"] = pd.util.hash_pandas_object(dup_df, index=False)

C:\Users\mogr1\AppData\Local\Temp\ipykernel_22792\3666866866.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dup_df["_row_hash"] = pd.util.hash_pandas_object(dup_df, index=False)

In [14]:
dup_df["_row_hash"].value_counts().head()

_row_hash
18039619856456918358    3
2004784000541655177     3
12324305981263051344    3
2125547460172462369     3
9866021966799979217     3
Name: count, dtype: int64

In [15]:
example_hash = dup_df["_row_hash"].value_counts().index[0]

In [16]:
example_group = dup_df[dup_df["_row_hash"] == example_hash]
example_group

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,_row_hash
49,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,19:00 28 Jun,19h 55m,2 stops,In-flight meal not included,11150,18039619856456918358
4593,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,19:00 28 Jun,19h 55m,2 stops,In-flight meal not included,11150,18039619856456918358
10672,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,19:00 28 Jun,19h 55m,2 stops,In-flight meal not included,11150,18039619856456918358

In [17]:
example_group.nunique()

Airline            1
Date_of_Journey    1
Source             1
Destination        1
Route              1
Dep_Time           1
Arrival_Time       1
Duration           1
Total_Stops        1
Additional_Info    1
Price              1
_row_hash          1
dtype: int64

In [18]:
row1 = example_group.iloc[0]
row2 = example_group.iloc[1]

row1 == row2

Airline            True
Date_of_Journey    True
Source             True
Destination        True
Route              True
Dep_Time           True
Arrival_Time       True
Duration           True
Total_Stops        True
Additional_Info    True
Price              True
_row_hash          True
dtype: bool

In [19]:
df.loc[example_group.index].duplicated()

49       False
4593      True
10672     True
dtype: bool