## Target Guided Ordinal Encoding

The encoding of categorical variable into numerical variable is based on its relationship (mean or median) with the target variable.
Used when we have a categorical variable with a large number of unique categories and they are important for the model.
We rank categories from lowest to highest impact on the target.

In [17]:
import pandas as pd

## Create DataFrame with categorical and a target variable
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 180, 300, 250, 180, 320]
})
df

       city  price
0  New York    200
1    London    180
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [18]:
# Finding mean prices for each city

mean_price = df.groupby('city')['price'].mean()
mean_price.to_dict()

{'London': 180.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [19]:
df['city_encoded'] = df['city'].map(mean_price.to_dict())

In [20]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    180         180.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [21]:
## we no longer need city names
df = df.drop('city',axis=1)
df

   price  city_encoded
0    200         190.0
1    180         180.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0